# Lobby world
lobby-world: "world"
# Enable tips to let players get displayed tips periodically
tips: true
# If enabled, only worlds listed here will be included in HungerGames
whitelist-worlds: false
# Worlds that will be excluded from list
ignored-worlds:
  - "world_nether"
  - "world_the_end"
  # Add more worlds to exclude
# Reset world, this restores the world to a previous state
reset-world: false
# Enable or disable players spectating on death, default is false, set to true to enable
spectating: true
# Database Settings
database-url: ""
database-user: ""
database-password: ""
