# Lobby world
lobby-world: "world"
# Enable tips to let players get displayed tips periodically
tips: true
# If enabled, only worlds listed here will be included in HungerGames
whitelist-worlds: false
# Worlds that will be excluded from list
ignored-worlds:
  - "world_nether"
  - "world_the_end"
  # Add more worlds to exclude
# Reset world, this restores the world to a previous state
reset-world: false
# Enable or disable players spectating on death, default is true, set to false to disable
spectating: true
# Allows the creation of custom teams
custom-teams: false
# Database Settings, used for stats tracking
# THIS FEATURE IS IN BETA! BUGS REGARDING THIS ARE TO BE EXPECTED
database:
  enabled: false
  url: ""
  user: ""
  password: ""
