# Lobby world
lobby-world: "world"
# Enable tips to let players get displayed tips periodically
tips: true
# Worlds that will be ignored by HungerGames
ignored-worlds:
  - "world_nether"
  - "world_the_end"
  # More worlds
# Reset world, this restores the world to a previous state
reset-world: false
# Enable or disable players spectating on death, default is false, set to true to enable
spectating: true
